package com.interguess.autoimpl.api.field;

import org.jetbrains.annotations.NotNull;

import javax.lang.model.type.TypeMirror;

/**
 * Represents a field that is generated by the auto-implementation process.
 * This interface provides methods to retrieve the type and name of the generated field.
 */
public interface GeneratedField {

    /**
     * The type of the generated field.
     *
     * @return the type of the field as a TypeMirror
     */
    @NotNull TypeMirror getType();

    /**
     * The name of the generated field.
     *
     * @return the name of the field as a String
     */
    @NotNull String getName();
}
